import React, { useState } from 'react';
import {
    Box, Typography, Container, TextField, Button, Paper,
    CircularProgress, Accordion, AccordionSummary, AccordionDetails,
    Select, MenuItem, FormControl, InputLabel, Grid, Chip
} from '@mui/material';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRightLeft, ChevronDown, AlertCircle, Copy, Check, Plus, Trash2 } from 'lucide-react';
import ToolPageLayout from '../../components/layout/ToolPageLayout';

const API_BASE = `${import.meta.env.VITE_API_BASE_URL}/web/publicTool`;

const REDIRECT_TYPES = [
    { value: '301', label: '301 - Permanent Redirect', desc: 'SEO-friendly. Passes link equity. Use when permanently moving a page.' },
    { value: '302', label: '302 - Temporary Redirect', desc: 'Does not pass link equity. Use for temporary moves or A/B testing.' },
    { value: '303', label: '303 - See Other', desc: 'Used after POST requests to redirect to a confirmation page.' },
    { value: '307', label: '307 - Temporary Redirect', desc: 'Preserves the HTTP method. Strict temporary redirect.' },
    { value: '308', label: '308 - Permanent Redirect', desc: 'Preserves the HTTP method. Strict permanent redirect.' },
];

const FAQS = [
    { q: 'What is an .htaccess file?', a: '.htaccess is a distributed configuration file used on Apache web servers. It allows directory-level configuration overrides including URL redirects, password protection, and custom error pages.' },
    { q: 'What is the difference between 301 and 302 redirects?', a: 'A 301 redirect is permanent and tells search engines to transfer link equity to the new URL. A 302 is temporary and does not transfer link equity — search engines keep indexing the original URL.' },
    { q: 'How do I add redirects to my .htaccess file?', a: 'Paste the generated redirect rules into your .htaccess file (typically at the root of your web server document directory). Place them before any existing RewriteRule directives.' },
    { q: 'Do redirects affect SEO?', a: '301 redirects preserve most SEO value (link equity) when moving pages. Always use 301 redirects when permanently changing URLs to avoid losing rankings.' },
    { q: 'What is mod_rewrite?', a: 'mod_rewrite is an Apache module that provides URL rewriting capabilities. The RewriteEngine On directive activates it, and RewriteRule/RewriteCond are used to define redirect patterns.' },
];

interface RedirectRule {
    fromPath: string;
    toUrl: string;
    type: string;
}

const HtaccessRedirectPage: React.FC = () => {
    const [rules, setRules] = useState<RedirectRule[]>([{ fromPath: '', toUrl: '', type: '301' }]);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    const addRule = () => setRules([...rules, { fromPath: '', toUrl: '', type: '301' }]);
    const removeRule = (i: number) => setRules(rules.filter((_, idx) => idx !== i));
    const updateRule = (i: number, field: keyof RedirectRule, value: string) =>
        setRules(rules.map((r, idx) => idx === i ? { ...r, [field]: value } : r));

    const handleGenerate = async () => {
        const validRules = rules.filter(r => r.fromPath && r.toUrl);
        if (!validRules.length) return;
        setLoading(true); setError(null); setResult(null);
        try {
            const res = await fetch(`${API_BASE}/htaccess-redirect-generator`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ redirects: validRules }),
            });
            const data = await res.json();
            if (data.status === 'success' || data.status === 200 || data.code === 'SUCCESS') setResult(data.data);
            else setError(data.message || 'Request failed');
        } catch {
            // Fallback: generate locally
            const htaccess = generateLocally(validRules);
            setResult({ htaccess, generated: true });
        } finally {
            setLoading(false);
        }
    };

    const generateLocally = (redirectRules: RedirectRule[]) => {
        const lines = ['# Generated by LeasePacket Tools', 'RewriteEngine On', ''];
        redirectRules.forEach(rule => {
            const from = rule.fromPath.startsWith('/') ? rule.fromPath.slice(1) : rule.fromPath;
            lines.push(`RewriteRule ^${escapeRegex(from)}$ ${rule.toUrl} [R=${rule.type},L]`);
        });
        return lines.join('\n');
    };

    const escapeRegex = (s: string) => s.replace(/[.+*?^${}()|[\]\\]/g, '\\$&');

    const outputText = result ? (typeof result === 'string' ? result : result.htaccess || result.content || JSON.stringify(result, null, 2)) : '';

    const handleCopy = () => {
        navigator.clipboard.writeText(outputText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <ToolPageLayout>
            <Box sx={{ py: { xs: 6, md: 10 }, textAlign: 'center', px: 2, background: 'linear-gradient(180deg, rgba(231,76,60,0.07) 0%, transparent 100%)' }}>
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
                    <Box sx={{ display: 'inline-flex', p: 2, bgcolor: 'rgba(231,76,60,0.1)', borderRadius: '16px', mb: 3, border: '1px solid rgba(231,76,60,0.25)' }}>
                        <ArrowRightLeft size={36} color="#E74C3C" />
                    </Box>
                    <Typography variant="h2" sx={{ fontWeight: 900, mb: 2, fontSize: { xs: '2rem', md: '3rem' } }}>HTACCESS Redirect Generator</Typography>
                    <Typography sx={{ color: 'rgba(255,255,255,0.6)', maxWidth: 600, mx: 'auto', fontSize: '1.1rem' }}>
                        Generate Apache .htaccess redirect rules instantly. Add multiple redirects with 301/302/307/308 status codes ready to paste into your server config.
                    </Typography>
                </motion.div>
            </Box>

            <Container maxWidth="md" sx={{ pb: 8 }}>
                <Paper elevation={0} sx={{ bgcolor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '20px', p: { xs: 3, md: 5 }, mb: 4 }}>
                    <Typography variant="h6" sx={{ fontWeight: 700, mb: 3, color: '#e2e8f0' }}>Redirect Rules</Typography>

                    {rules.map((rule, i) => (
                        <Box key={i} sx={{ p: 2.5, bgcolor: 'rgba(0,0,0,0.15)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: '12px', mb: 2 }}>
                            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                                <Chip label={`Rule ${i + 1}`} size="small" sx={{ bgcolor: 'rgba(231,76,60,0.1)', color: '#E74C3C', border: '1px solid rgba(231,76,60,0.2)', fontWeight: 700 }} />
                                {rules.length > 1 && (
                                    <Button size="small" onClick={() => removeRule(i)} sx={{ color: 'rgba(255,255,255,0.3)', minWidth: 0, '&:hover': { color: '#E74C3C' } }}>
                                        <Trash2 size={15} />
                                    </Button>
                                )}
                            </Box>
                            <Grid container spacing={2}>
                                <Grid size={{ xs: 12, sm: 4 }}>
                                    <FormControl fullWidth>
                                        <InputLabel sx={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.85rem' }}>Redirect Type</InputLabel>
                                        <Select value={rule.type} label="Redirect Type" onChange={(e) => updateRule(i, 'type', e.target.value)}
                                            sx={{ color: '#fff', bgcolor: 'rgba(0,0,0,0.2)', '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.1)' }, '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(231,76,60,0.5)' }, '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderColor: '#E74C3C' }, '& .MuiSvgIcon-root': { color: 'rgba(255,255,255,0.5)' } }}
                                            MenuProps={{ PaperProps: { sx: { bgcolor: '#1a2744', border: '1px solid rgba(255,255,255,0.1)' } } }}>
                                            {REDIRECT_TYPES.map(t => <MenuItem key={t.value} value={t.value} sx={{ color: '#e2e8f0', '&:hover': { bgcolor: 'rgba(255,255,255,0.05)' } }}>{t.label}</MenuItem>)}
                                        </Select>
                                    </FormControl>
                                </Grid>
                                <Grid size={{ xs: 12, sm: 4 }}>
                                    <TextField fullWidth label="From Path" placeholder="/old-page"
                                        value={rule.fromPath} onChange={(e) => updateRule(i, 'fromPath', e.target.value)}
                                        InputLabelProps={{ sx: { color: 'rgba(255,255,255,0.4)', fontSize: '0.85rem' } }}
                                        sx={{ '& .MuiOutlinedInput-root': { color: '#fff', bgcolor: 'rgba(0,0,0,0.2)', '& fieldset': { borderColor: 'rgba(255,255,255,0.1)' }, '&:hover fieldset': { borderColor: 'rgba(231,76,60,0.5)' }, '&.Mui-focused fieldset': { borderColor: '#E74C3C' } } }} />
                                </Grid>
                                <Grid size={{ xs: 12, sm: 4 }}>
                                    <TextField fullWidth label="To URL" placeholder="https://example.com/new-page"
                                        value={rule.toUrl} onChange={(e) => updateRule(i, 'toUrl', e.target.value)}
                                        InputLabelProps={{ sx: { color: 'rgba(255,255,255,0.4)', fontSize: '0.85rem' } }}
                                        sx={{ '& .MuiOutlinedInput-root': { color: '#fff', bgcolor: 'rgba(0,0,0,0.2)', '& fieldset': { borderColor: 'rgba(255,255,255,0.1)' }, '&:hover fieldset': { borderColor: 'rgba(231,76,60,0.5)' }, '&.Mui-focused fieldset': { borderColor: '#E74C3C' } } }} />
                                </Grid>
                            </Grid>
                            {/* Type description */}
                            <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.3)', mt: 1, display: 'block' }}>
                                {REDIRECT_TYPES.find(t => t.value === rule.type)?.desc}
                            </Typography>
                        </Box>
                    ))}

                    <Button startIcon={<Plus size={16} />} onClick={addRule} sx={{ color: 'rgba(255,255,255,0.5)', textTransform: 'none', mb: 3, '&:hover': { color: '#E74C3C' } }}>
                        Add Another Rule
                    </Button>

                    <Button variant="contained" fullWidth onClick={handleGenerate} disabled={loading || !rules.some(r => r.fromPath && r.toUrl)}
                        sx={{ bgcolor: '#E74C3C', py: 1.5, fontWeight: 700, borderRadius: '10px', fontSize: '1rem', '&:hover': { bgcolor: '#c0392b' }, '&.Mui-disabled': { bgcolor: 'rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.3)' } }}>
                        {loading ? <CircularProgress size={22} color="inherit" /> : 'Generate .htaccess Rules'}
                    </Button>
                </Paper>

                <AnimatePresence>
                    {error && (
                        <motion.div key="err" initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
                            <Paper elevation={0} sx={{ p: 3, bgcolor: 'rgba(231,76,60,0.08)', border: '1px solid rgba(231,76,60,0.25)', borderRadius: '14px', mb: 4, display: 'flex', gap: 1.5 }}>
                                <AlertCircle size={20} color="#E74C3C" style={{ flexShrink: 0 }} />
                                <Typography sx={{ color: '#E74C3C' }}>{error}</Typography>
                            </Paper>
                        </motion.div>
                    )}
                    {result && (
                        <motion.div key="res" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
                            <Paper elevation={0} sx={{ p: { xs: 3, md: 4 }, bgcolor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '20px', mb: 4 }}>
                                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                                    <Typography variant="h6" sx={{ fontWeight: 700 }}>Generated .htaccess Rules</Typography>
                                    <Button size="small" startIcon={copied ? <Check size={14} /> : <Copy size={14} />} onClick={handleCopy}
                                        sx={{ color: copied ? '#2ECC71' : 'rgba(255,255,255,0.5)', textTransform: 'none', borderRadius: '8px', '&:hover': { color: '#E74C3C' } }}>
                                        {copied ? 'Copied!' : 'Copy'}
                                    </Button>
                                </Box>
                                <Box sx={{ p: 3, bgcolor: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', fontFamily: 'monospace', fontSize: '0.85rem', color: '#a8c5e8', whiteSpace: 'pre-wrap', lineHeight: 1.8 }}>
                                    {outputText}
                                </Box>
                                <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.3)', mt: 1.5, display: 'block' }}>
                                    Paste these rules into your .htaccess file. Make sure mod_rewrite is enabled on your Apache server.
                                </Typography>
                            </Paper>
                        </motion.div>
                    )}
                </AnimatePresence>

                <Paper elevation={0} sx={{ p: { xs: 3, md: 4 }, bgcolor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '20px', mb: 4 }}>
                    <Typography variant="h5" sx={{ fontWeight: 800, mb: 3 }}>How to Use</Typography>
                    {[
                        { step: '1', title: 'Choose Redirect Type', desc: 'Select 301 for permanent redirects (best for SEO), 302 for temporary, or 307/308 for method-preserving redirects.' },
                        { step: '2', title: 'Enter Source & Destination', desc: 'Enter the old path (e.g., /old-page) and the full destination URL (e.g., https://example.com/new-page).' },
                        { step: '3', title: 'Add More Rules', desc: 'Click "Add Another Rule" to create multiple redirects in a single .htaccess file.' },
                        { step: '4', title: 'Generate & Deploy', desc: 'Click Generate, copy the output, and paste it into your server\'s .htaccess file. Test after deploying.' },
                    ].map((item) => (
                        <Box key={item.step} sx={{ display: 'flex', gap: 2.5, mb: 2.5 }}>
                            <Box sx={{ width: 32, height: 32, borderRadius: '8px', bgcolor: 'rgba(231,76,60,0.15)', border: '1px solid rgba(231,76,60,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                <Typography sx={{ color: '#E74C3C', fontWeight: 800, fontSize: '0.85rem' }}>{item.step}</Typography>
                            </Box>
                            <Box><Typography sx={{ fontWeight: 700, mb: 0.5 }}>{item.title}</Typography><Typography sx={{ color: 'rgba(255,255,255,0.55)', fontSize: '0.9rem', lineHeight: 1.6 }}>{item.desc}</Typography></Box>
                        </Box>
                    ))}
                </Paper>

                <Typography variant="h5" sx={{ fontWeight: 800, mb: 3 }}>Frequently Asked Questions</Typography>
                {FAQS.map((faq, i) => (
                    <Accordion key={i} disableGutters elevation={0} sx={{ bgcolor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px !important', mb: 1.5, '&:before': { display: 'none' } }}>
                        <AccordionSummary expandIcon={<ChevronDown size={18} color="rgba(255,255,255,0.5)" />} sx={{ px: 3, py: 1.5 }}>
                            <Typography sx={{ fontWeight: 600, color: '#e2e8f0' }}>{faq.q}</Typography>
                        </AccordionSummary>
                        <AccordionDetails sx={{ px: 3, pb: 2.5 }}>
                            <Typography sx={{ color: 'rgba(255,255,255,0.6)', lineHeight: 1.7 }}>{faq.a}</Typography>
                        </AccordionDetails>
                    </Accordion>
                ))}
            </Container>
        </ToolPageLayout>
    );
};

export default HtaccessRedirectPage;
